### ISSUE TITLE
1.2.0 release

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#1433]
Here's what I think we need to target for the 1.2.0 release.

1. [x] 1. Complete https://github.com/dotnet/orleans/pull/963, so that we are done with interceptors
2. [x] 2. Complete https://github.com/dotnet/orleans/pull/1375 to have a first usable version of the EventHub stream adapter
3. [x] 3. Provide enough helper methods (similar to https://github.com/dotnet/orleans/pull/1411) for clean and easy programmatic configuration. 
4. [x] 4. https://github.com/dotnet/orleans/issues/1439 The litmus test for 3 is ability to convert all samples to programmatic config and remove all config files from them. Updated sample will have to wait in a [WIP] PR ready to be merged after we publish 1.2.0 NuGets.
5. [x] 5. https://github.com/dotnet/orleans/issues/1145 Add a single codegen NuGet, and turn the existing "template" NuGets into empty meta-packages.
6. [x] 6. https://github.com/dotnet/orleans/issues/1437 Update VSIX interface and implementation project templates to use the new codegen NuGet package from 5. Samples in 4 should be updated to use these templates.
7. [x] 7. https://github.com/dotnet/orleans/issues/1438 Update VSIX dev/test host template to use programmatic config instead of config files. Samples in 4 should be updated to use this template.
8. [x] 8. Complete https://github.com/dotnet/orleans/issues/1378 since this may be a breaking change for people explicitly catching and unwrapping `AggregateException`.
9. [x] 9. https://github.com/dotnet/orleans/issues/1440 Fix VSIX project templates for VB and F#
10. [x] 10. https://github.com/dotnet/orleans/issues/1416 AzureQueueStreamProvider violates at-least-once delivery
11. [x] 11. https://github.com/dotnet/orleans/pull/1429 Remove dead client producer from pub sub
12. [x] 12. https://github.com/dotnet/orleans/pull/1669 Stream consumers on lost clients

We'll publish a beta of 1.2.0 NuGets for a short testing period (a week?)

Did I miss something important?

**Comment by jdom** [comment]
exception propagation (#1378) is almost finished by #1415, but I think it's worth making sure it goes into 1.2.0, since it's a breaking change we want to do as early as possible

**Comment by sergeybykov** [comment]
@jdom Agreed. Added as #8 to the list.

**Comment by sergeybykov** [comment]
Added #9 for https://github.com/dotnet/orleans/issues/1440 Fix VSIX project templates for VB and F#.

**Comment by gabikliot** [comment]
It would be nice to include https://github.com/dotnet/orleans/issues/1416. If we can agree with @jason-bragg  on the strategy, I can quickly fix it.

**Comment by sergeybykov** [comment]
@gabikliot Added as 10.

**Comment by gabikliot** [comment]
I think @jason-bragg will have the fix for #1429 ready for this release.

**Comment by sergeybykov** [comment]
Yeah, I already added it as 11.

**Comment by sergeybykov** [comment]
Released.
