### ISSUE TITLE
Minimize/eliminate the usage of code generation in Orleans

### ISSUE THREAD

**Issue by gabikliot** [dotnet/orleans#474]
Orleans uses code generation in a number of places.

Our goal is to minimize the usage of code generation in Orleans and maybe even completely eliminate it.
The reasons to minimize code generation usage are:
1) The code that generates code is hard to maintain. Need to generate different code for each target language (C#, F#, VB) (first mentioned [here](https://github.com/dotnet/orleans/issues/42#issuecomment-71910491)).
2) Generated code is harder to test, harder to do dependency injection. 
3) "Developers don't like generated code". That's the feedback we got from some of your customers. Generated code appears as "magic" to some, harder to follow (#42).
4) Eliminating code generation will make Orleans more portable. For example, it will make porting Orleans to coreclr easier (#368), since coreclr does not support CodeDOM like the full .NET does, and will make #40 unnecessary.

Places where we use code gen today in Orleans:
- [x] `GetGrain` calls in Concrete Grain factories. Done. (#469).
- [x] Concrete Grain factories. The work is already in progress to eliminate those (#469).
- [x] State classes. The work is already in progress to eliminate those (#465).
- [ ] Concrete Grain References (what is usually known in RPC terminology as stubs).
- [ ] Grain invokers (what is usually known in RPC terminology as skeletons).
- [ ] Orleans auto generated serializers.

**Comment by sergeybykov** [comment]
Now that we switched to the Roslyn-based codegen, do we need to do anything else here? I don't see a proposal for an alternative for the last three items on the list.

**Comment by gabikliot** [comment]
I would still keep it open, as (if everyone does indeed agree on the merit of Minimize/eliminate the usage of code generation in Orleans) it serves as an argument against: https://github.com/dotnet/orleans/pull/965#issuecomment-162415524.

As for concrete proposals for the last 3 items: I did propose in the past the idea of dynamic dispatch object for "Concrete Grain References". I don't have the implementation to backup that proposal though.

**Comment by gabikliot** [comment]
I think we can close this issue.
For the first 3 points we indeed eliminated the usage of code generation in Orleans.
For the last 3 points instead we went with the path of **improving the code generation in Orleans, via Roslyn-based codegen**.
