### ISSUE TITLE
Orleans 7.0 Docs Plan Checklist

### ISSUE THREAD

**Issue by bradygaster** [dotnet/orleans#8203]
Creating this issue as a top-level checklist we can use to keep track of the content problems we need to solve, ideas we want to implement, and goals we want to accomplish. 

* [x] David and Alex tend to work from this list: https://github.com/dotnet/docs/issues?q=is%3Aopen+is%3Aissue+label%3Adotnet-orleans%2Fprod
* [x] Tabular view of all the Orleans NuGet packages and what would prompt you to want to pull them into your app's codebase. 
* [ ] Create a zone pivot for Orleans 3 and basically put everything we have in the docs today into that moniker. 
* [x] Create an Orleans 7 zone pivot for the changes we'll make specific to Orleans 7.
* [x] The serialization doc is the first conceptual doc we should do a pivot specific to Orleans versions for as there's no commonality between 3.x serialization and 7 serialization. 
* [x] We need a pivot in the Grain docs as `OnActivated` and `OnDeactivated` have changed signatures. 
* [x] Change the TOC title for the what's new article to be "Migrate from 3.x to 7.0" since it's more specific to migration than a what's-new article. 
* [ ] We need a walk-through that's not "magic CLI or Bicep" to show folks the actual step-by-step of deploying an app using Orleans. 
* [ ] We should write a walk-through on using Windows Services and SQL Server for an on-prem implementation of Orleans. 
* [ ] We should write a general hosting guidance doc, and in it, inform folks how to host on-prem, as well as on App Service, ACA, and Kubernetes. Essentially a high-level checklist of things they'll need to do inside of each one of the areas. 

cc @IEvangelist @alexwolfmsft @benjaminpetit @ReubenBond @adityamandaleeka FYI

**Comment by Cloud33** [comment]
Great Plan

**Comment by jonathan** [comment]
All of that sounds great and would greatly help my team. We are currently building a service in Orleans and doing our best with old docs and sample apps.

I'd also like to add that there needs to be better guidance on writing unit tests for Orleans 7. It seems that a couple of people over at OrleansContrib/OrleansTestKit have been working on this but the effort has stalled: https://github.com/OrleansContrib/OrleansTestKit/issues/123

**Comment by bbehrens** [comment]
> All of that sounds great and would greatly help my team. We are currently building a service in Orleans and doing our best with old docs and sample apps.
> 
> I'd also like to add that there needs to be better guidance on writing unit tests for Orleans 7. It seems that a couple of people over at OrleansContrib/OrleansTestKit have been working on this but the effort has stalled: [OrleansContrib/OrleansTestKit#123](https://github.com/OrleansContrib/OrleansTestKit/issues/123)

This is fantastic.  Thank you! +1 to additional testing support for Orleans.
