### ISSUE TITLE
[EPIC] Papercuts to fix for 8.0

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#8257]
This is an issue to log and track *papercuts*: small annoyances/inconveniences which developers often run into. Please feel free to add to the list and to pick off items on the list to fix.

* [ ] Silo shutdown takes too long, even in dev/test scenarios with a single silo and no persistence
* [ ] Orleans calls issued before the silo/client has fully initialized should either throw or wait until startup has completed - waiting is probably nicer UX, as long as there's still a timeout to say that it's waiting for initialization.
* [ ] Logging noise: Logging that `CleanupDefunctSiloEntries` is not supported is unnecessary, especially as a warning. We should also not throw an exception and should implement it on most/all providers
* [ ] Logging noise: "No implementation of IHostEnvironmentStatistics was found. Load shedding will not work yet"
  * [ ] Add config validator to only warn/error if `LoadSheddingOptions.LoadSheddingEnabled` is true

Follow-up from #7099
